import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        {/* Left component: Can shrink */}
        <div className="border-2 border-blue-400 w-[20%]">
          controls instructions
        </div>

        {/* Middle component: Has a min-width but can grow */}
        <div className="border-2 border-green-400 flex-grow flex justify-center items-center">
          {children}
        </div>

        {/* Right component: Can shrink */}
        <div className="border-2 border-red-400 w-[20%]">
          leaderboard
        </div>
      </body>
    </html>
  );
}
