import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Instructions from "./components/instructions";

export const metadata: Metadata = {
  title: "Sudokyou - Sudoku For You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen overflow-hidden ">
      <body className="w-full h-screen flex flex-col items-center bg-white dark:bg-black overflow-hidden">
        <Navbar />
          {/* Outer flex container */}
          <div className="h-full w-full flex flex-row justify-center">

            {/* Middle component */}
            <div className="h-full xl:w-[1280px] lg:w-[1024px] w-full flex flex-row justify-center ">

              {/* Main content area */}
              <div className="h-full lg:w-[1024px] w-full p-1 overflow-hidden">
                {children}
              </div>

              {/* Right component */}
              <div className="h-full lg:w-[256px] hidden lg:block pt-2 pb-2 select-none overflow-y-scroll">
                <Instructions />
              </div>
            </div>
          </div>
      </body>
    </html>
  );
}
